### ISSUE TITLE
Message Information for group message

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/Applozic-Android-SDK#122]

**Comment by priyadarshi** [comment]
- [ ] App  is crashing in offline mode
- [ ] Showing user names , create group, search user and refresh/delete option on top
- [ ] File with text overriding issue

**Comment by priyadarshi** [comment]
Log Detail for 1st issue:
05-07 15:27:53.882  19318-19336/com.mobicomkit.sample.debug W/System.err? at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-07 15:27:53.882  19318-19336/com.mobicomkit.sample.debug W/System.err? at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-07 15:27:53.882  19318-19336/com.mobicomkit.sample.debug W/System.err? at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-07 15:27:53.882  19318-19336/com.mobicomkit.sample.debug W/System.err? at java.lang.Thread.run(Thread.java:818)
05-07 15:27:53.906  19318-19318/com.mobicomkit.sample.debug D/AndroidRuntime? Shutting down VM
    --------- beginning of crash
05-07 15:27:53.907  19318-19318/com.mobicomkit.sample.debug E/AndroidRuntime? FATAL EXCEPTION: main
    Process: com.mobicomkit.sample.debug, PID: 19318
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.applozic.mobicomkit.api.conversation.MessageInfoResponse.getReadByUserList()' on a null object reference
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MessageInfoFragment$MessageInfoAsyncTask.onPostExecute(MessageInfoFragment.java:197)
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MessageInfoFragment$MessageInfoAsyncTask.onPostExecute(MessageInfoFragment.java:168)
            at android.os.AsyncTask.finish(AsyncTask.java:651)
            at android.os.AsyncTask.-wrap1(AsyncTask.java)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by priyadarshi** [comment]
Log Detail for 2nd issue:
05-07 16:04:10.588  27817-27817/com.mobicomkit.sample.debug I/System.out? message.isGroupMessage()  :::true Type:::true Menu Item:::true
05-07 16:04:12.131  27817-27817/com.mobicomkit.sample.debug E/InputEventReceiver? Exception dispatching input event.
05-07 16:04:12.131  27817-27817/com.mobicomkit.sample.debug E/MessageQueue-JNI? Exception in MessageQueue callback: handleReceiveCallback
05-07 16:04:12.134  27817-27817/com.mobicomkit.sample.debug E/MessageQueue-JNI? java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.applozic.mobicomkit.api.attachment.FileMeta.getContentType()' on a null object reference
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MessageInfoFragment.setupAttachmentView(MessageInfoFragment.java:388)
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MessageInfoFragment.onCreateView(MessageInfoFragment.java:100)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
            at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.addFragment(ConversationActivity.java:167)
            at com.applozic.mobicomkit.uiwidgets.conversation.ConversationUIService.startMessageInfoFragment(ConversationUIService.java:547)
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.onContextItemSelected(MobiComConversationFragment.java:1421)
            at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:2085)
            at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2173)
            at android.support.v4.app.FragmentController.dispatchContextItemSelected(FragmentController.java:308)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:370)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
            at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
            at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
            at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:5013)
            at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
            at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
            at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
            at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108)
            at android.widget.AdapterView.performItemClick(AdapterView.java:310)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
            at android.widget.AbsListView.onTouchUp(AbsListView.java:3915)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3680)
            at android.view.View.dispatchTouchEvent(View.java:9300)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
            at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)

**Comment by adarshmishra** [comment]
@priyadarshi, please test.

**Comment by priyadarshi** [comment]
- [ ] Disable all permission then try to see message info of file, it will crash

Log Detail:

05-11 22:40:02.628  12159-12221/com.mobicomkit.sample.debug I/conversation﹕ @@@@@@@@@@@@@@@@@isChannel{key=53979, name='Group_1', adminKey='rohan', type=2, unreadCount=0, userCount=0, conversationPxy=null, contacts=[]}
05-11 22:40:02.628  12159-12221/com.mobicomkit.sample.debug I/contact is @@@@@﹕ isnull
05-11 22:40:02.629  12159-12224/com.mobicomkit.sample.debug E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #5
    Process: com.mobicomkit.sample.debug, PID: 12159
    java.lang.RuntimeException: An error occurred while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:309)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
            at com.applozic.mobicommons.commons.core.utils.Utils.getMetaDataValue(Utils.java:230)
            at com.applozic.mobicomkit.api.MobiComKitClientService.getApplicationKey(MobiComKitClientService.java:115)
            at com.applozic.mobicomkit.api.conversation.MobiComConversationService.<init>(MobiComConversationService.java:64)
            at com.applozic.mobicomkit.api.conversation.MobiComMessageService.<init>(MobiComMessageService.java:63)
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MessageInfoFragment$MessageInfoAsyncTask.doInBackground(MessageInfoFragment.java:205)
            at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MessageInfoFragment$MessageInfoAsyncTask.doInBackground(MessageInfoFragment.java:188)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
05-11 22:40:02.630  12159-12221/com.mobicomkit.sample.debug I/cursor.moveToFirst()﹕ cursor.moveToFirst()false
05-11 22:40:02.819  12159-12159/com.mobicomkit.sample.debug I/contactId﹕ contactId checkingranjeet
05-11 22:40:02.857  12159-12223/com.mobicomkit.sample.debug E/BitmapFactory﹕ Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/Applozic/image/.Thumbnail/AMIfv94FcxZWSCaK

**Comment by priyadarshi** [comment]
Verified.
