### ISSUE TITLE
OOM in contacts image profile

### ISSUE THREAD

**Issue by adarshmishra** [AppLozic/Applozic-Android-SDK#152]
04-08 13:18:48.533    5782-5782/? E/dalvikvm-heap﹕ Out of memory on a 4002016-byte allocation.
04-08 13:18:48.584    5782-5782/? E/InputEventReceiver﹕ Exception dispatching input event.
04-08 13:18:48.604    5782-5782/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
            at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:522)
            at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:540)
            at com.applozic.mobicomkit.contact.MobiComVCFParser.stringToBitMap(MobiComVCFParser.java:106)
            at com.applozic.mobicomkit.contact.MobiComVCFParser.parseCVFContactData(MobiComVCFParser.java:63)
            at com.applozic.mobicomkit.uiwidgets.conversation.adapter.DetailedConversationAdapter.setupContactShareView(DetailedConversationAdapter.java:587)
            at com.applozic.mobicomkit.uiwidgets.conversation.adapter.DetailedConversationAdapter.getView(DetailedConversationAdapter.java:572)
            at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
            at android.widget.AbsListView.obtainView(AbsListView.java:2588)
            at android.widget.ListView.makeAndAddView(ListView.java:1840)
            at android.widget.ListView.fillUp(ListView.java:715)
            at android.widget.ListView.fillGap(ListView.java:654)
            at android.widget.AbsListView.trackMotionScroll(AbsListView.java:6535)
            at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3664)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:4492)
            at android.view.View.dispatchTouchEvent(View.java:7677)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2395)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2401)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2305)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1575)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2470)
            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2253)
            at android.view.View.dispatchPointerEvent(View.java:7875)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3978)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3862)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5105)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5084)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5182)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.view.InputEventReceiver.nativ
04-08 13:18:48.964   1430-14576/? E/java.gralloc﹕ GRALLOC ALLOC flags 933

**Comment by sunip123** [comment]
#Verified
