### ISSUE TITLE
NullPointerException in MobiComConversationFragment

### ISSUE THREAD

**Issue by yzheka** [AppLozic/Applozic-Android-SDK#187]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                              at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.updateChannelTitleAndSubTitle(MobiComConversationFragment.java:1622)
                                                              at com.applozic.mobicomkit.uiwidgets.conversation.ConversationUIService.updateChannelSync(ConversationUIService.java:471)
                                                              at com.applozic.mobicomkit.uiwidgets.conversation.MobiComKitBroadcastReceiver.onReceive(MobiComKitBroadcastReceiver.java:112)
                                                              at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
                                                              at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
                                                              at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:148)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Just launched a Group chat Activity

**Comment by Sunilkumarr** [comment]
@yzheka Hi, this is fixed  in new version 4.56 commit hash is https://github.com/AppLozic/Applozic-Android-SDK/commit/1482be13619a75f4ee252c0190987a18068ae341 merge the changes
