### ISSUE TITLE
Notification Crash

### ISSUE THREAD

**Issue by monishagarwal215** [AppLozic/Applozic-Android-SDK#189]
Hi,

I have integrated a chat module.

When my app is in background state and user send chat from web module.

And as soon as notification comes it crashes.

Logs are here 
Process: com.lookatme, PID: 2603
                                                            java.lang.NullPointerException
                                                                at java.lang.Class.classForName(Native Method)
                                                                at java.lang.Class.forName(Class.java:309)
                                                                at java.lang.Class.forName(Class.java:273)
                                                                at com.applozic.mobicomkit.api.notification.NotificationService.notifyUser(NotificationService.java:88)
                                                                at com.applozic.mobicomkit.uiwidgets.notification.MTNotificationBroadcastReceiver$1.run(MTNotificationBroadcastReceiver.java:58)
                                                                at java.lang.Thread.run(Thread.java:818)

And I have added activity and service in manifest:
<receiver android:name="com.applozic.mobicomkit.uiwidgets.notification.MTNotificationBroadcastReceiver">
            <intent-filter>
                <action android:name="${applicationId}.send.notification" />
            </intent-filter>
        </receiver>

**Comment by Sunilkumarr** [comment]
@monishagarwal215  Hi you have missed to add the 
```
<meta-data
            android:name="activity.open.on.notification"
            android:value="com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity" />
```
and documentation link is this [Android documentation]( https://www.applozic.com/docs/android-chat-sdk.html ) and verify once if anything is missing

**Comment by monishagarwal215** [comment]
After adding it is crashing again.

**Comment by monishagarwal215** [comment]
Thanks it worked now for me..

**Comment by monishagarwal215** [comment]
@Sunilkumarr It crashes when app is in killed state. If it is in background then it works..

**Comment by Sunilkumarr** [comment]
@monishagarwal215 please send us the log

**Comment by monishagarwal215** [comment]
Same logs...

**Comment by monishagarwal215** [comment]
I have not added a meta data tag for notifcation icon.
