### ISSUE TITLE
Sporadic Crash in Chatrooms

### ISSUE THREAD

**Issue by InI4** [AppLozic/Applozic-Android-SDK#198]
It doesn't happen often. Seems to happen after returning to app after a while. 

E/AndroidRuntime: FATAL EXCEPTION: main

```
    java.lang.RuntimeException: Unable to start activity
```

ComponentInfo{de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.ChannelInfoActivity}: 
android.view.InflateException: Binary XML file line #17: Error inflating class android.support.design.widget.CollapsingToolbarLayout

```
        at
```

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)

```
        at
```

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)

```
        at
```

android.app.ActivityThread.access$700(ActivityThread.java:150)

```
        at
```

android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)

```
        at android.os.Handler.dispatchMessage(Handler.java:99)

        at android.os.Looper.loop(Looper.java:137)

        at android.app.ActivityThread.main(ActivityThread.java:5279)

        at java.lang.reflect.Method.invokeNative(Native Method)

        at java.lang.reflect.Method.invoke(Method.java:511)

        at
```

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)

```
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)

        at
```

de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

```
        at dalvik.system.NativeStart.main(Native Method)

     Caused by: android.view.InflateException: Binary XML file line
```
#17: Error inflating class

android.support.design.widget.CollapsingToolbarLayout

```
        at
```

android.view.LayoutInflater.createView(LayoutInflater.java:619)

```
        at
```

android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)

```
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)

        at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)

        at
```

de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native
Method)

```
        at
```

de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)

```
        at android.view.LayoutInflater.inflate(Native Method)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

        at
```

android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)

```
        at
```

android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)

```
        at
```

com.applozic.mobicomkit.uiwidgets.conversation.activity.ChannelInfoActivity.onCreate(ChannelInfoActivity.java:105)

```
        at android.app.Activity.performCreate(Activity.java:5267)

        at
```

android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)

```
        at
```

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)

```
        at
```

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)

```
        at
```

android.app.ActivityThread.access$700(ActivityThread.java:150)

```
        at
```

android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)

```
        at android.os.Handler.dispatchMessage(Handler.java:99)

        at android.os.Looper.loop(Looper.java:137)

        at android.app.ActivityThread.main(ActivityThread.java:5279)

        at java.lang.reflect.Method.invokeNative(Native Method)

        at java.lang.reflect.Method.invoke(Method.java:511)

        at
```

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 

```
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)

        at
```

de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

```
        at dalvik.system.NativeStart.main(Native Method)

     Caused by: java.lang.reflect.InvocationTargetException

        at java.lang.reflect.Constructor.constructNative(Native Method)

        at
```

java.lang.reflect.Constructor.newInstance(Constructor.java:417)

```
        at
```

android.view.LayoutInflater.createView(LayoutInflater.java:593)

```
        at
```

android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)

```
        at
```

android.view.LayoutInflater.rInflate(LayoutInflater.java:752)

```
        at
```

android.view.LayoutInflater.rInflate(LayoutInflater.java:760)

```
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)

        at
```

de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native
Method)

```
        at
```

de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 

```
        at android.view.LayoutInflater.inflate(Native Method)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

        at
```

android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 

```
        at
```

android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 

```
        at
```

com.applozic.mobicomkit.uiwidgets.conversation.activity.ChannelInfoActivity.onCreate(ChannelInfoActivity.java:105) 

```
        at android.app.Activity.performCreate(Activity.java:5267)

        at
```

android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)

```
        at
```

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)

```
        at
```

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)

```
        at
```

android.app.ActivityThread.access$700(ActivityThread.java:150)

```
        at
```

android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)

```
        at android.os.Handler.dispatchMessage(Handler.java:99)

        at android.os.Looper.loop(Looper.java:137)

        at android.app.ActivityThread.main(ActivityThread.java:5279)

        at java.lang.reflect.Method.invokeNative(Native Method)

        at java.lang.reflect.Method.invoke(Method.java:511)

        at
```

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 

```
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)

        at
```

de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

```
        at dalvik.system.NativeStart.main(Native Method)

     Caused by: java.lang.NoSuchMethodError: 
```

android.support.v4.graphics.drawable.DrawableCompat.setLayoutDirection

```
        at
```

android.support.design.widget.CollapsingToolbarLayout.setStatusBarScrim(CollapsingToolbarLayout.java:663)

```
        at
```

android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:197)

```
        at
```

android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java:132)

```
        at java.lang.reflect.Constructor.constructNative(Native Method)

        at
```

java.lang.reflect.Constructor.newInstance(Constructor.java:417)

```
        at
```

android.view.LayoutInflater.createView(LayoutInflater.java:593)

```
        at
```

android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:693)

```
        at
```

android.view.LayoutInflater.rInflate(LayoutInflater.java:752)

```
        at
```

android.view.LayoutInflater.rInflate(LayoutInflater.java:760)

```
        at android.view.LayoutInflater.inflate(LayoutInflater.java:495)

        at
```

de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native
Method)

```
        at
```

de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631) 

```
        at android.view.LayoutInflater.inflate(Native Method)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)

        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

        at
```

android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 

```
        at
```

android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 

```
        at
```

com.applozic.mobicomkit.uiwidgets.conversation.activity.ChannelInfoActivity.onCreate(ChannelInfoActivity.java:105) 

```
        at android.app.Activity.performCreate(Activity.java:5267)

        at
```

android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)

```
        at
```

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)

```
        at
```

android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)

```
        at
```

android.app.ActivityThread.access$700(ActivityThread.java:150)

```
        at
```

android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)

```
        at android.os.Handler.dispatchMessage(Handler.java:99)

        at android.os.Looper.loop(Looper.java:137)

        at android.app.ActivityThread.main(ActivityThread.java:5279)

        at java.lang.reflect.Method.invokeNative(Native Method)

        at java.lang.reflect.Method.invoke(Method.java:511)

        at
```

com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 

```
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)

        at
```

de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

```
        at dalvik.system.NativeStart.main(Native Method)
```

`

**Comment by Sunilkumarr** [comment]
@InI4 Can i get the version of support libs  your using?

**Comment by InI4** [comment]
I am currently at this one: compile 'com.android.support:support-v4:23.4.0'
