### ISSUE TITLE
Crash on location sharing

### ISSUE THREAD

**Issue by InI4** [AppLozic/Applozic-Android-SDK#199]
This one repeats all the time, but might well be related to #198 i.e. support lib dependand

10-16 11:19:52.781 6285-6285/de.spieleck.app.badgers.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: de.spieleck.app.badgers.debug, PID: 6285
                                                                             java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/data/de.spieleck.app.badgers.debug/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-9.6.1_45169c41b3f4f65501acacbaa39f402e52c8ede9-classes.dex)
                                                                                 at com.google.android.gms.maps.model.CameraPosition.<init>(Unknown Source)
                                                                                 at com.google.android.gms.maps.model.CameraPosition.<init>(Unknown Source)
                                                                                 at com.google.android.gms.maps.model.CameraPosition$Builder.build(Unknown Source)
                                                                                 at com.google.android.gms.maps.model.CameraPosition.createFromAttributes(Unknown Source)
                                                                                 at com.google.android.gms.maps.GoogleMapOptions.createFromAttributes(Unknown Source)
                                                                                 at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
                                                                                 at android.support.v4.app.Fragment.onInflate(Fragment.java:1174)
                                                                                 at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2414)
                                                                                 at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                                 at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:376)
                                                                                 at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                                 at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                 at com.applozic.mobicomkit.uiwidgets.conversation.activity.MobicomLocationActivity.onCreate(MobicomLocationActivity.java:59)
                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-16 11:19:52.782 1545-1556/system_process W/ActivityManager:   Force finishing activity de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.MobicomLocationActivity
10-16 11:19:52.784 1545-1556/system_process W/ActivityManager:   Force finishing activity de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity
10-16 11:19:53.285 1545-1559/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{347e86e u0 de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.MobicomLocationActivity t1423 f}
10-16 11:19:55.569 1545-4884/system_process E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f201e58e840
10-16 11:19:55.617 1545-1583/system_process W/InputDispatcher: channel 'dba4f03 de.spieleck.app.badgers.debug/de.spieleck.app.badgers.MainOSMActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-16 11:19:55.617 1545-1583/system_process E/InputDispatcher: channel 'dba4f03 de.spieleck.app.badgers.debug/de.spieleck.app.badgers.MainOSMActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 11:19:55.618 1545-1583/system_process W/InputDispatcher: channel 'b502161 de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-16 11:19:55.618 1545-1583/system_process E/InputDispatcher: channel 'b502161 de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-16 11:19:55.619 1545-2680/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'dba4f03 de.spieleck.app.badgers.debug/de.spieleck.app.badgers.MainOSMActivity (server)'
10-16 11:19:55.628 1545-1879/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel 'b502161 de.spieleck.app.badgers.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity (server)'
10-16 11:19:55.631 1545-1950/system_process W/ActivityManager: Scheduling restart of crashed service de.spieleck.app.badgers.debug/com.applozic.mobicomkit.api.conversation.ApplozicMqttIntentService in 5710ms
10-16 11:19:55.688 6976-6976/de.spieleck.app.badgers.debug W/System: ClassLoader referenced unknown path: /data/app/de.spieleck.app.badgers.debug-1/lib/x86_64
10-16 11:19:56.019 6976-6976/de.spieleck.app.badgers.debug W/System: ClassLoader referenced unknown path: /data/app/de.spieleck.app.badgers.debug-1/lib/x86_64
10-16 11:19:56.105 6976-6976/de.spieleck.app.badgers.debug W/InstanceID/Rpc: Found 10007
10-16 11:19:56.176 6976-6976/de.spieleck.app.badgers.debug W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-16 11:19:56.342 1545-1564/system_process W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
10-16 11:19:56.559 1545-1564/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
10-16 11:19:56.575 1191-1191/? W/SurfaceFlinger: couldn't log to binary event log: overflow.

**Comment by Sunilkumarr** [comment]
@InI4 Hi can you try by enabling Mutlidex in your app if its not enabled?[Multidex link] (http://stackoverflow.com/questions/26609734/how-to-enable-multidexing-with-the-new-android-multidex-support-library)  .

**Comment by Sunilkumarr** [comment]
@InI4 Can you attach your app complete build.gradle file ?

**Comment by InI4** [comment]
Oops, I missed your comment. I am not multidexing.

`
apply plugin: 'com.android.application'
// this seems to hurt now (11.12.2015):

def bumpVersionCount = false;

gradle.taskGraph.whenReady {
    bumpVersionCount = gradle.taskGraph.hasTask(':app:assembleRelease');
    println("*** potential bumpVersionCount=" + bumpVersionCount)
}

android {
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/ECLIPSE_.SF'
        exclude 'META-INF/ECLIPSE_.RSA'
    }
    compileSdkVersion 23
    buildToolsVersion '24.0.0'
    // dexOptions {
        // incremental true
        // javaMaxHeapSize "4g"
    // }

    defaultConfig {
        applicationId "de.spieleck.app.badgers"
        minSdkVersion 17
        targetSdkVersion 23
        versionCode readVersionCode
        versionName gitVersionName // "0.0.6"
        // not necessary any more, or again :-(
        // multiDexEnabled true
    }
    buildTypes {
        applicationVariants.all { variant ->
            if (variant.name == android.buildTypes.release.name) variant.outputs.each { output ->
                def outputFile = output.outputFile;
                // def nn = outputFile.name.replace(".apk", "_" + gitVersionName + "_" + readVersionCode + ".apk");
                def nn = "releases/" + outputFile.name.replace(".apk", "_" + readVersionCode + ".apk");
                output.outputFile = new File(outputFile.parent, nn);
            }
        }
        debug {
            applicationIdSuffix ".debug"
            minifyEnabled false // true is slow  and makes finding source harder ..
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'proguard-strip-log.txt'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    // compile fileTree(include: ['*.jar'], dir: 'libs')
    // implied by client ... compile project(path: ':common')
    compile project(path: ':client')
    // Testing dependencies
    // androidTestCompile 'com.android.support.test.espresso:espresso-core:*'
    // androidTestCompile 'com.android.support.test:runner:0.2'
    // androidTestCompile 'com.android.support:support-annotations:23.1.1'
    compile 'javax.annotation:jsr250-api:1.0'
    // compile 'org.osmdroid:osmdroid-android:5.4.1:release@aar'
    compile 'org.osmdroid:osmdroid-android:5.6-SNAPSHOT:debug@aar'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.android.support:support-v4:23.4.0'
    // 9.2 exists also for firebase-messaging, however the emulators are not happy!
    compile "com.google.firebase:firebase-messaging:9.6.1"
    compile "com.google.firebase:firebase-config:9.6.1"
    compile 'com.google.android.gms:play-services-appinvite:9.6.1'
    compile 'com.google.android.gms:play-services-location:9.6.1'
    //
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
    compile 'com.yalantis:ucrop:2.2.0'
    // compile 'com.google.android.gms:play-services-appindexing:9.0.2'
    // compile 'com.github.wooplr:Spotlight:1.2.2'
    compile project(path: ':spotlight')
    compile 'io.github.kobakei:ratethisapp:1.1.0'
    compile 'com.applozic.communication.uiwidget:mobicomkitui:4.62'
}

gradle.buildFinished { buildResult ->
    println "BUILD " + readVersionCode + " FINISHED; failure=" + buildResult.failure
    if (bumpVersionCount && buildResult.failure == null) {
        copy {
            from buildDir.getPath() + "/outputs/mapping/release"
            into buildDir.getPath() + '/../releases/'
            rename 'mapping.txt', 'mapping_' + readVersionCode + '.txt'
            include 'mapping.txt'
        }
        println("copied " + readVersionCode);
        def newVersionCode = 0
        try {
            newVersionCode = readVersionCode + 1
            versionProps['VERSION_CODE'] = newVersionCode.toString()
            versionProps.store(versionCountPropsFile.newWriter(), null)
        } catch (panik) {
            println(panik)
        }
        println("*** version count increment! " + readVersionCode + " -> " + newVersionCode)
    } else {
        println("*** no version count increment.")
    }

}

//
// I have problems with different releases and google-services.json
// therefore replaced by manual values!!
// https://developers.google.com/android/guides/google-services-plugin
//
// apply plugin: 'com.google.gms.google-services'
`
