### ISSUE TITLE
Audio Call not Working 

### ISSUE THREAD

**Issue by iamsharzil** [AppLozic/Applozic-Android-SDK#226]
Hi there,
When I click on audio call it brings me back to start fragment_ecommerce.xml screen and I want to create a separate registration page. Please help me out.

**Comment by Sunilkumarr** [comment]
@iamsharzil 
Remove this meta data from android manifest 

```
 <meta-data
            android:name="activity.open.on.call.button.click"
            android:value="com.applozic.mobicomkit.sample.MainActivity" />
```
This below link is complete documentation  link   
[https://www.applozic.com/docs/android-chat-sdk.html#add-applozic-chat-to-existing-app](https://www.applozic.com/docs/android-chat-sdk.html#add-applozic-chat-to-existing-app
)

and go with option b from the above doc link 

b) Chat SDK with Audio/Video.

`compile 'com.applozic.communication.uiwidget:audiovideo:1.1'
`

This are the settings and activity you need to add for enabling the audio video call option 
[https://www.applozic.com/docs/android-chat-sdk.html#audio-video-call-setup]( https://www.applozic.com/docs/android-chat-sdk.html#audio-video-call-setup
)
 

For more ui customization  for Audio video you can clone the audio video sdk with messaging from this link
[https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-AV-Sample](https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-AV-Sample)

**Comment by iamsharzil** [comment]
@Sunilkumarr Hey thanks for your reply. I want a separate activity for Sign Up and Login. Can you please help me?

**Comment by Sunilkumarr** [comment]
@iamsharzil  Check this below activity for SignUp / Login change the ui from this activity create a another Signup activity as same

https://github.com/AppLozic/Applozic-Android-SDK/blob/master/app/src/main/java/com/applozic/mobicomkit/sample/LoginActivity.java

This is the code used for Signup/Login  user to applozic :
[https://www.applozic.com/docs/android-chat-sdk.html#step-3-login-register-user](https://www.applozic.com/docs/android-chat-sdk.html#step-3-login-register-user
)

**Comment by iamsharzil** [comment]
@Sunilkumarr  I have created SignUpActivity.java and activity_register.xml with some changes and copied all the code from LoginActivity.java but then the app was getting close. Can you please correct me?

**Comment by Sunilkumarr** [comment]
@iamsharzil can you please send the logs what are you getting.

**Comment by iamsharzil** [comment]
@Sunilkumarr 
In LoginActivity.java I have added this. Now the app gets close immediately without showing any screen. I have define the activity in manifest file also.

`  mEmailSignUpButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent myintent = new Intent(LoginActivity.this , RegisterActivity.class);
                startActivity(myintent);
            }
        });`

03-28 19:01:39.789 6742-6742/com.mobicomkit.sample E/FirebaseApp: Firebase API initialization failure.
                                                                  java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                      at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                      at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5247)
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4836)
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4767)
                                                                      at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                                      at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                                      at android.app.ActivityThread.access$1600(ActivityThread.java:165)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:150)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
                                                                      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
                                                                   Caused by: java.lang.NoSuchMethodError: No static method zzz(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/data/com.mobicomkit.sample/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-10.0.1_fc1968edcab2fd7ea56b2695de1ffdc7c1447316-classes.dex)
                                                                      at com.google.android.gms.measurement.internal.zzx.zzbd(Unknown Source)
                                                                      at com.google.android.gms.measurement.AppMeasurement.getInstance(Unknown Source)
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                      at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1748) 
                                                                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1723) 
                                                                      at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                      at android.app.ActivityThread.installProvider(ActivityThread.java:5247) 
                                                                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4836) 
                                                                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4767) 
                                                                      at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334) 
                                                                      at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                                      at android.app.ActivityThread.access$1600(ActivityThread.java:165) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:150) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) 
                                                                      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
03-28 19:01:39.796 6742-6742/com.mobicomkit.sample I/FirebaseInitProvider: FirebaseApp initialization successful
03-28 19:01:40.058 6742-6742/com.mobicomkit.sample I/CrashlyticsCore: Initializing Crashlytics 2.3.10.127
                                                                      
                                                                      
                                                                      [ 03-28 19:01:40.102  3729: 3729 E/         ]
                                                                      process stopped due to unexpected signal 13
03-28 19:01:40.200 6742-6742/com.mobicomkit.sample I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
03-28 19:01:40.305 6742-6742/com.mobicomkit.sample I/HwSecImmHelper: mSecurityInputMethodService is null
03-28 19:01:40.424 6742-6865/com.mobicomkit.sample E/HAL: load: id=gralloc != hmi->id=gralloc
03-28 19:01:40.425 6742-6865/com.mobicomkit.sample I/OpenGLRenderer: Initialized EGL, version 1.4
03-28 19:01:40.506 6742-6742/com.mobicomkit.sample I/HwSecImmHelper: mSecurityInputMethodService is null
03-28 19:01:41.226 6742-6864/com.mobicomkit.sample I/System: core_booster, getBoosterConfig = false
                                                             
                                                             [ 03-28 19:01:41.300  3729: 3729 E/         ]
                                                             process stopped due to unexpected signal 13
03-28 19:01:41.594 6742-6864/com.mobicomkit.sample I/System: core_booster, getBoosterConfig = false
03-28 19:01:41.721 6742-6862/com.mobicomkit.sample I/System: core_booster, getBoosterConfig = false
03-28 19:01:41.740 6742-6742/com.mobicomkit.sample I/Process: Sending signal. PID: 6742 SIG: 9

**Comment by Sunilkumarr** [comment]
@iamsharzil can you send the sample project code

**Comment by iamsharzil** [comment]
​
 Applozic.zip
<https://drive.google.com/file/d/0B6V94EkoYGtfVjJSc2piaWg1QzA/view?usp=drive_web>
​

**Comment by iamsharzil** [comment]
@Sunilkumarr Please help me out. Thank You

**Comment by Sunilkumarr** [comment]
@iamsharzil Find the link https://drive.google.com/file/d/0Bybp9bc7ou6mQS1UbDhRc1Jzc3c/view it was giving error in the signup button which was added but not accessed in the activity

**Comment by iamsharzil** [comment]
Hey thank you so much. I asked many people for help but none of them were
interested but You solved it. Thank you. God bless you.
