### ISSUE TITLE
adding voice call and videocall error gradle

### ISSUE THREAD

**Issue by Widiyanto** [AppLozic/Applozic-Android-SDK#255]
`Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 10 cannot be smaller than version 16 declared in library [com.applozic.communication.uiwidget:audiovideo:1.2] C:\Users\Widiyanto02\.android\build-cache\893c7a2f08e0b0ead2f58ee8b648fbde5602d97c\output\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="applozic.com.audiovideo" to force usage
`

I change minimum sdk to 16 and get new error
`Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/applozic/mobicomkit/uiwidgets/ActivityLifecycleHandler.class`

**Comment by Sunilkumarr** [comment]
@Widiyanto Can you paste your app  build.gradle file ?

**Comment by Widiyanto** [comment]
Thanks for reply.
this my build.gradle

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
repositories {
    maven { url 'https://maven.fabric.io/public' }
}
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"


    defaultConfig {
        applicationId "com.mobicomkit.sample"
        minSdkVersion 10
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {

        abortOnError false

    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/ECLIPSE_.SF'
        exclude 'META-INF/ECLIPSE_.RSA'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':mobicomkitui') //Note: use this for customization
    compile 'com.applozic.communication.uiwidget:audiovideo:1.2'
   // compile 'com.applozic.communication.uiwidget:mobicomkitui:4.84' //Note:use this in case customization is not required
    compile 'com.android.support:support-v4:25.1.1'
    compile 'com.android.support:appcompat-v7:25.1.1'
    //compile 'com.facebook.android:facebook-android-sdk:4.1.0'
    compile 'com.android.support:design:25.1.1'
    compile 'com.android.support:multidex:1.0.1'
    //compile 'com.android.support:cardview-v7:22.0'
    //compile 'com.android.support:recyclerview-v7:22.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.7@aar') {
        transitive = true;
    }
}
apply plugin: 'com.google.gms.google-services'

**Comment by Sunilkumarr** [comment]
@Widiyanto comment this line   
compile project(':mobicomkitui') //Note: use this for customization 

For audio video sample sdk code you can check this  link 

https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-AV-Sample

**Comment by Widiyanto** [comment]
Thanks a lot for response.
Refer to [https://github.com/AppLozic/Applozic-Android-Chat-Sample/tree/master/Applozic-Android-AV-Sample](url)

I get error when call

06-13 16:49:30.392 28738-28738/? D/AndroidRuntime: procName from cmdline: com.mobicomkit.sample
06-13 16:49:30.392 28738-28738/? E/AndroidRuntime: in writeCrashedAppName, pkgName :com.mobicomkit.sample
06-13 16:49:30.392 28738-28738/? D/AndroidRuntime: file written successfully with content: com.mobicomkit.sample StringBuffer : ;com.mobicomkit.sample
06-13 16:49:30.392 28738-28738/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mobicomkit.sample, PID: 28738
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mobicomkit.sample/com.applozic.audiovideo.activity.AudioCallActivityV2}: java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5021)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat
                                                       at com.twilio.video.Preconditions.checkState(Preconditions.java:453)
                                                       at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:70)
                                                       at com.twilio.video.LocalVideoTrack.create(LocalVideoTrack.java:44)
                                                       at com.applozic.audiovideo.activity.AudioCallActivityV2.createAudioAndVideoTracks(AudioCallActivityV2.java:236)
                                                       at com.applozic.audiovideo.activity.AudioCallActivityV2.onCreate(AudioCallActivityV2.java:224)
                                                       at android.app.Activity.performCreate(Activity.java:5318)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5021) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643) 
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by Sunilkumarr** [comment]
@Widiyanto Your trying in emulator or real device ? can you tell the  device android version also

**Comment by Widiyanto** [comment]
i am using bluestack android version 4.4.2

**Comment by Sunilkumarr** [comment]
@Widiyanto Can you try in real device ?

**Comment by Widiyanto** [comment]
In real device is work fine.
But on simulator not, and login or register with real device have textbox no telpn, on simulator not have

**Comment by Sunilkumarr** [comment]
@Widiyanto Can you tell the configuration used for creating the emulator will try the same here and you can test on real devices for now

**Comment by Widiyanto** [comment]
I don't change configuration from example, for now only change Application_key  `<string name="application_key">2eff5bc7b6d4cce581717f946bb17fb54</string>` 

Summary:
- Voice call and video call on real devices are work 
- Voice call and video call on simulator are not work
- on real device, LoginActivity have phone number
- on simulator, LoginActivity don't have phone number

**Comment by Sunilkumarr** [comment]
@Widiyanto Phone number is not required for call only userId is required and for Voice call and video call on simulator are not work currently -- > its working my simulator  can you please try in android studio emulator ?

**Comment by Widiyanto** [comment]
thanks a lot @Sunilkumarr , 
I will try on android studio simulator.
One more question.
Applogic provide API in JSON or XML for get Contact, Message?? because my backend need data like thats

**Comment by Widiyanto** [comment]
Because I can't see thats

**Comment by Widiyanto** [comment]
Now i can see in platform APIs. thank for all sir.
God bless u
