### ISSUE TITLE
A crash: ApplozicAudioRecordManager.java line 67 com.applozic.mobicomkit.uiwidgets.attachmentview.ApplozicAudioRecordManager

### ISSUE THREAD

**Issue by osama-taha** [AppLozic/Applozic-Android-SDK#292]
## Expected Results
 No crash

## Actual Results
crashed.

## Steps to Reproduce

I pressed the record button,  without permission for recording audio...
The permission dialog popped, I clicked the 'allow' and the app crashed....
After re opening the app, it worked...

Applozic Android SDK version:  5.1.1
Android device: Samsung Galaxy S7
Android OS version: Android 7.0

## logs:

Fatal Exception: java.lang.NullPointerException
       at java.io.File.<init>(File.java:262)
       at com.applozic.mobicomkit.uiwidgets.attachmentview.ApplozicAudioRecordManager.cancelAudio(ApplozicAudioRecordManager.java:67)
       at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment$5.onTouch(MobiComConversationFragment.java:508)
       at android.view.View.dispatchTouchEvent(View.java:10727)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:509)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3226)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.appsee.q.dispatchTouchEvent(x:756)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:471)
       at android.view.View.dispatchPointerEvent(View.java:10960)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5075)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4927)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4458)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4511)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4477)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4610)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4485)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4667)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4458)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4511)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4477)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4485)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4458)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6960)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6899)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6860)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7070)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7034)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7097)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:632)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6692)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by Sunilkumarr** [comment]
@osama-taha  you can update to latest  v5.1.2

**Comment by osama-taha** [comment]
thanks.
