### ISSUE TITLE
Android 8 - com.applozic.mobicomkit.broadcast.ConnectivityReceiver  crash 

### ISSUE THREAD

**Issue by osama-taha** [AppLozic/Applozic-Android-SDK#296]
# Logs:

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.applozic.mobicomkit.broadcast.ConnectivityReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.hp.printosforpsp/com.applozic.mobicomkit.api.conversation.ApplozicIntentService (has extras) }: app is in background uid UidRecord{7ed1581 u0a94 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3259)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.hp.printosforpsp/com.applozic.mobicomkit.api.conversation.ApplozicIntentService (has extras) }: app is in background uid UidRecord{7ed1581 u0a94 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
       at android.app.ContextImpl.startService(ContextImpl.java:1461)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at android.content.ContextWrapper.startService(ContextWrapper.java:644)
       at com.applozic.mobicomkit.broadcast.ConnectivityReceiver.onReceive(ConnectivityReceiver.java:44)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6541)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

# Android devices: Pixel,Pixel XL, Nexus 5X
# Android OS version: 8.0.0 / 8.1.0
# Applozic version: applozic latest version

**Comment by razmaimon** [comment]
any updates on this issue?

**Comment by osama-taha** [comment]
@Sunilkumarr 

we have experienced this issue before in devices running Android 8.x ...

The ConnectivityReceiver that receives the ACTION_BOOT_COMPLETED could call startForegroundService() instead of startService() for Android 8.0+:

public class ConnectivityReceiver extends BroadcastReceiver {

  @Override
  public void onReceive(Context context, Intent intent) {

    if (Build.VERSION.SDK_INT>=Build.VERSION_CODES.O) {
      context.startForegroundService(serviceIntent);
    }
    else {
      context.startService(serviceIntent);
    }
  }
}

**Comment by Sunilkumarr** [comment]
@razmaimon i'm working on this to support android 8  will update on this soon after changes are done

**Comment by Sunilkumarr** [comment]
@osama-taha @razmaimon  Update sdk to android 8, you need to  merge the changes from this issue : https://github.com/AppLozic/Applozic-Android-SDK/issues/300
