### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException        at com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter.getView(QuickConversationAdapter.java:165)

### ISSUE THREAD

**Issue by osama-taha** [AppLozic/Applozic-Android-SDK#309]
Hi, please take a look:

App crashed due to the following exception:

Fatal Exception: java.lang.NullPointerException
       at com.applozic.mobicomkit.uiwidgets.conversation.adapter.QuickConversationAdapter.getView(QuickConversationAdapter.java:165)
       at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
       at android.widget.AbsListView.obtainView(AbsListView.java:2181)
       at android.widget.ListView.makeAndAddView(ListView.java:1880)
       at android.widget.ListView.fillSpecific(ListView.java:1351)
       at android.widget.ListView.fillSpecific(ListView.java:1342)
       at android.widget.ListView.layoutChildren(ListView.java:1673)
       at android.widget.AbsListView.onLayout(AbsListView.java:2016)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:452)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:452)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:452)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:452)
       at android.view.View.layout(View.java:14471)
       at android.view.ViewGroup.layout(ViewGroup.java:4562)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1986)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1009)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5508)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:730)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:5225)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Sunilkumarr** [comment]
@osama-taha it's fixed in latest version you can use latest SDK v5.6.4 tag: https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/5.6.4
