### ISSUE TITLE
How to update password user using url?

### ISSUE THREAD

**Issue by Widiyanto** [AppLozic/Applozic-Android-SDK#321]
http://apps.applozic.com/rest/ws/user/update/password?oldPassword=qwerty1234&newPassword=mypass1234

how to get 
Application-Key : xxxxxx
Authorization : how get this?

**Comment by mhrpatel12** [comment]
You can get more info for passing headers for admin/application user on our [docs](https://docs.applozic.com/docs/chat-api-authentication#section-headers) page.

**Comment by mhrpatel12** [comment]
We have method available in Android SDK. UserService.getInstance(this).processUpdateUserPassword("oldPassword","newPassword");

**Comment by mhrpatel12** [comment]
Also, this needs to be called from AsyncTask.

**Comment by Widiyanto** [comment]
I trying call in asyntask

class Task1 extends AsyncTask<Void, Void, String> {

        @Override
        protected void onPreExecute()
        {
            super.onPreExecute();
        }

        @Override
        protected String doInBackground(Void... arg0)
        {
            return UserService.getInstance(getActivity()).updateDisplayNameORImageLink("wida","","","");
        }

        @Override
        protected void onPostExecute(String result)
        {
            super.onPostExecute(result);

        }
    }


04-12 02:06:48.206 29053-29130/id.jkt.wot E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                            Process: id.jkt.wot, PID: 29053
                                                            java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.lang.StackOverflowError: stack size 1038KB
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                                at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(UserService.java:188)
                                                            	at com.applozic.mobicomkit.api.account.user.UserService.updateDisplayNameORImageLink(

**Comment by mhrpatel12** [comment]
how you are calling this AsyncTask ?

**Comment by Widiyanto** [comment]
`class Task1 extends AsyncTask<Void, Void, String> {

    @Override
    protected void onPreExecute()
    {
        super.onPreExecute();
    }

    @Override
    protected String doInBackground(Void... arg0)
    {
        return UserService.getInstance(getActivity()).updateDisplayNameORImageLink("wida","","","");
    }

    @Override
    protected void onPostExecute(String result)
    {
        super.onPostExecute(result);

    }
}
`

`void updateUser(){
new Task1 ().execute();
}
`

**Comment by mhrpatel12** [comment]
please call this method from UserService. 
https://github.com/AppLozic/Applozic-Android-SDK/blob/master/mobicomkit/src/main/java/com/applozic/mobicomkit/api/account/user/UserService.java#L263

**Comment by Widiyanto** [comment]
Just call UserService.getInstance(getActivity()).updateDisplayNameORImageLink("wida","","","");
??
Without asyntask?

**Comment by mhrpatel12** [comment]
updateDisplayNameORImageLink must be called from AsyncTask.
Modify your AsyncTask doInBackground method with following.

    return UserService.getInstance(getActivity()).updateDisplayNameORImageLink("displayName", "profileImageLink", "localURL", "status", "contactNumber");

**Comment by mhrpatel12** [comment]
it's calling our internal method recursively, which is causing an error.
You can use the method with five parameters which I shared in previous comment.

**Comment by Widiyanto** [comment]
Okay thanks, I think it can be filled with 4 parameters
