### ISSUE TITLE
Loading please wait taking forever

### ISSUE THREAD

**Issue by kherlopian1** [AppLozic/Applozic-Android-SDK#332]
I get this below in my logcat. here is video to prove things too https://streamable.com/gp8zj

java.net.MalformedURLException: For input string: "8080null"
07-11 09:51:53.207 4719-4854/com.netvariant.rasheedalshahran W/System.err:     at java.net.URL.<init>(URL.java:624)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.applozic.mobicomkit.api.MobiComKitClientService.openHttpConnection(MobiComKitClientService.java:106)
        at com.applozic.mobicomkit.api.attachment.FileClientService.downloadBitmap(FileClientService.java:266)
        at com.applozic.mobicomkit.contact.AppContactService.downloadContactImage(AppContactService.java:137)
07-11 09:51:53.208 4719-4854/com.netvariant.rasheedalshahran W/System.err:     at com.applozic.mobicomkit.uiwidgets.people.contact.ContactSelectionFragment$1.processBitmap(ContactSelectionFragment.java:157)
        at com.applozic.mobicommons.commons.image.ImageLoader$BitmapWorkerTask.doInBackground(ImageLoader.java:399)
        at com.applozic.mobicommons.commons.image.ImageLoader$BitmapWorkerTask.doInBackground(ImageLoader.java:333)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
07-11 09:51:53.209 4719-4854/com.netvariant.rasheedalshahran W/System.err: Caused by: java.lang.NumberFormatException: For input string: "8080null"
        at java.lang.Integer.parseInt(Integer.java:608)
        at java.lang.Integer.parseInt(Integer.java:643)
        at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:233)
        at java.net.URL.<init>(URL.java:619)
    	... 14 more

**Comment by kherlopian1** [comment]
After 6 minutes, loader goes away. but 6 minutes.

**Comment by devashishmamgain** [comment]
@kherlopian1 this error ' For input string: "8080null"' can happen in case if the image url passed to Applozic is not correct, we just checked records for your account and found image url passed to Applozic as:
http://192.168.0.125:8080null
http://192.168.0.125:8080null
http://192.168.0.125:8080null

Please correct the image urls passed for the user's profile picture.

**Comment by kherlopian1** [comment]
hi there, and the loader issue is originated from that? why should loader await images????

**Comment by kherlopian1** [comment]
Hi , can u remove those urls to me? i am deleting all users , which users have those links?

**Comment by devashishmamgain** [comment]
not sure about loader issue, loader issue team will get back on the support email where the issue is raised from your team. For above mentioned error log, problem is with image urls passed.

**Comment by devashishmamgain** [comment]
@DevShourya please export the data for users who have invalid image urls. @kherlopian1 we will send this data over email.

**Comment by kherlopian1** [comment]
The error thing is fixed. I hope the loader issue is fixed too.It feels like its awaiting images to download, then loader disappears. I have used in my app GLIDE library,  not sure how you guys loading images.
Thank You.
