### ISSUE TITLE
Unable to Capture Photo and Record Video using Applozic SDK

### ISSUE THREAD

**Issue by hammad-tariq** [AppLozic/Applozic-Android-SDK#367]
I am trying to send Image/Photo using the Camera button in the attachment.
But when I click on the Camera or Video button. this is a stack trace.

W/System.err: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/ProjectName/image/JPEG_20190414_130606_.jpeg
W/System.err:     at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:418)
W/System.err:     at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.imageCapture(ConversationActivity.java:1194)
        at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.processCameraAction(ConversationActivity.java:1147)
        at com.applozic.mobicomkit.uiwidgets.conversation.MultimediaOptionsGridView.executeMethod(MultimediaOptionsGridView.java:65)
        at com.applozic.mobicomkit.uiwidgets.conversation.MultimediaOptionsGridView$2.onItemClick(MultimediaOptionsGridView.java:54)
W/System.err:     at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3162)
        at android.widget.AbsListView$3.run(AbsListView.java:4100)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:795)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar

---- **And for Video Capturing** -----

W/System.err: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/ProjectName/video/VID_20190414_130714_.mp4
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
W/System.err:     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:418)
        at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.showVideoCapture(ConversationActivity.java:1253)
        at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.processVideoRecording(ConversationActivity.java:1164)
W/System.err:     at com.applozic.mobicomkit.uiwidgets.conversation.MultimediaOptionsGridView.executeMethod(MultimediaOptionsGridView.java:108)
        at com.applozic.mobicomkit.uiwidgets.conversation.MultimediaOptionsGridView$2.onItemClick(MultimediaOptionsGridView.java:54)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
W/System.err:     at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3162)
        at android.widget.AbsListView$3.run(AbsListView.java:4100)
        at android.os.Handler.handleCallback(Handler.java:795)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

-> I have tried using v. 5.30, 5.31 and 5.34

**Comment by Sunilkumarr** [comment]
Our team as replied through the mail regarding this issue. There was an issue with the external path set as only for the specific folder. You can set the external path to root folder as below it will have access

~~~
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="files"
        path="." />
</paths>
~~~
