### ISSUE TITLE
Crashes when opening a chat in devices with Android versions < API 24 

### ISSUE THREAD

**Issue by rohithThammaiah** [AppLozic/Applozic-Android-SDK#411]
## Goals
Fix a crash in API Level 23 and below

## Expected Results
Crashes whenever I try to open a particular chat in the devices with API levels mentioned above, is there some dependency I am missing.

## Actual Results
```FATAL EXCEPTION: main
    Process: com.techmash.playo.debug, PID: 24346
    java.lang.NoClassDefFoundError: java.util.function.BiFunction
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:479)
        at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:229)
        at java.lang.reflect.ArtMethod.getParameterTypes(ArtMethod.java:169)
        at java.lang.reflect.Method.getParameterTypes(Method.java:174)
        at java.lang.Class.getDeclaredMethods(Class.java:772)
        at java.io.ObjectStreamClass.computeSerialVersionUID(ObjectStreamClass.java:566)
        at java.io.ObjectStreamClass.createClassDesc(ObjectStreamClass.java:279)
        at java.io.ObjectStreamClass.lookupStreamClass(ObjectStreamClass.java:1087)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1554)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at android.os.Parcel.writeSerializable(Parcel.java:1383)
        at android.os.Parcel.writeValue(Parcel.java:1335)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1096)
        at android.os.Parcel.writeBundle(Parcel.java:663)
        at android.content.Intent.writeToParcel(Intent.java:7191)
        at android.app.ActivityManagerProxy.startService(ActivityManagerNative.java:3394)
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1705)
        at android.app.ContextImpl.startService(ContextImpl.java:1687)
        at android.content.ContextWrapper.startService(ContextWrapper.java:515)
        at androidx.core.app.JobIntentService$CompatWorkEnqueuer.enqueueWork(JobIntentService.java:182)
        at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:523)
        at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:501)
        at com.applozic.mobicomkit.api.conversation.ApplozicMqttIntentService.enqueueWork(ApplozicMqttIntentService.java:50)
        at com.applozic.mobicomkit.Applozic.subscribeToTyping(Applozic.java:183)
        at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.loadConversation(MobiComConversationFragment.java:1712)
        at com.applozic.mobicomkit.uiwidgets.conversation.fragment.MobiComConversationFragment.onResume(MobiComConversationFragment.java:2990)
        at com.applozic.mobicomkit.uiwidgets.conversation.fragment.ConversationFragment.onResume(ConversationFragment.java:199)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:2748)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:373)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1211)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
    	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.jav
```

## Steps to Reproduce
Whenever a ConversationActivity is called the above exception is thrown

## Code Sample
The SDK tightly coupled with our codebase. What sample can I share?

Applozic Android SDK version: 5.9.1

Android device: All devices < API 24 

Android OS version: < API 24 

Dependencies used with version: 
```
implementation fileTree(include: ['*.jar'], dir: 'libs')
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.appcompat:appcompat:1.1.0'
api 'com.google.code.gson:gson:2.8.5'
api 'com.google.firebase:firebase-messaging:20.0.0'
api 'com.google.android.gms:play-services-maps:17.0.0'
api 'com.google.android.gms:play-services-location:17.0.0'
implementation 'de.hdodenhof:circleimageview:2.2.0'
implementation 'com.google.android.material:material:1.0.0'
implementation 'com.theartofdev.edmodo:android-image-cropper:2.8.0'
implementation 'com.github.bumptech.glide:glide:4.11.0'
implementation 'androidx.cardview:cardview:1.0.0'
implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
//api project(':mobicomkit')
//Note: use this for customization
api 'com.applozic.communication.message:mobicomkit:5.80' //Note: use this in case customization is not required
```

**Comment by Sunilkumarr** [comment]
Hello @rohithThammaiah,

I have tried on API 23 and API 19 with our latest SDK [sample link](https://github.com/AppLozic/Applozic-Android-SDK) and version 5.9.1 with this commit link [id](https://github.com/AppLozic/Applozic-Android-SDK/commit/fce3c75390a248c77d89d914f64b5115c4931d18) sample project with source code I don't see this above crash. 

Can you share the sample by creating a sample project with the same target and add the source code module of applozic which is used in your project and with your app build.gradle Dependencies run the app and share it as a google drive link?

**Comment by rohithThammaiah** [comment]
Is there a scenario where this may happen due to Gradle dependency conflicts? We had migrated most of our libs to its latest version.

Note: This crash occurs only for Group conversation, one-to-one chat works fine

**Comment by Sunilkumarr** [comment]
I don't see a crash in a group or one to one chat with the above version 

As see java compiler not able to find the class run time 

It will be better if you could send us a sample with the source module and the same configuration of your app then I will try out with those configurations well.

**Comment by rohithThammaiah** [comment]
I have shared the source code and the debug apk with your support team

**Comment by rohithThammaiah** [comment]
Solved! It went away after disabling `coreLibraryDesugaring`
