### ISSUE TITLE
Crash on syncing with server 

### ISSUE THREAD

**Issue by billypap1** [AppLozic/Applozic-Android-SDK#428]
Hello, we are using this library to our project.

Project Language: Kotlin v1.5
Applozic-Android-SDK version: com.applozic.communication.message:mobicomkit:5.99.0
Android OS: 10 

We have follow the instructions exactly in order to integrate our app with Applozic Android SDK but we have an issue.
The user can successfully log in to Applozic Server but when the SDK (~  after 1 minute) trying to communicate with Applozic's server in order to sync (automatic procedure) the app is crashing.  

"crash due to doBackground() operation - proxy"

Is this a bug? 

Bellow is the full log:

```
I/ConversationIntent: Syncing messages service started: true
I/MobiComMessageService: Starting syncMessages for lastSyncTime: 1623096333604
I/HttpRequestUtils: Calling url: https://apps.applozic.com/rest/ws/message/sync?lastSyncTime=1623096333604
I/DpmTcmClient: RegisterTcmMonitor from: $Proxy0
I/MessageClientService: Sync call response: {..}
I/MobiComMessageService: Got sync response 108 messages.
I/MobiComMessageService: Going to call GCM device registration
I/BroadcastService: Sending message update broadcast for SYNC_MESSAGE, 1234563423434
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.test.project, PID: 5043
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.applozic.mobicomkit.api.notification.NotificationService.notifyUserForNormalMessage(NotificationService.java:386)
        at com.applozic.mobicomkit.broadcast.BroadcastService.sendNotificationBroadcast(BroadcastService.java:172)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.sendNotification(MobiComMessageService.java:248)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.addMTMessage(MobiComMessageService.java:219)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.processMessage(MobiComMessageService.java:136)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.syncMessages(MobiComMessageService.java:296)
        at com.applozic.mobicomkit.api.conversation.ConversationIntentService.onHandleWork(ConversationIntentService.java:84)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

```
Thanks

**Comment by billypap1** [comment]
Bellow is the full log: 

```
I/ConversationIntent: Syncing messages service started: true
I/MobiComMessageService: Starting syncMessages for lastSyncTime: 1623096333604
I/HttpRequestUtils: Calling url: https://apps.applozic.com/rest/ws/message/sync?lastSyncTime=1623096333604
I/DpmTcmClient: RegisterTcmMonitor from: $Proxy0
I/MessageClientService: Sync call response: {..}
I/MobiComMessageService: Got sync response 108 messages.
I/MobiComMessageService: Going to call GCM device registration
I/BroadcastService: Sending message update broadcast for SYNC_MESSAGE, 1234563423434
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.test.project, PID: 5043
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at com.applozic.mobicomkit.api.notification.NotificationService.notifyUserForNormalMessage(NotificationService.java:386)
        at com.applozic.mobicomkit.broadcast.BroadcastService.sendNotificationBroadcast(BroadcastService.java:172)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.sendNotification(MobiComMessageService.java:248)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.addMTMessage(MobiComMessageService.java:219)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.processMessage(MobiComMessageService.java:136)
        at com.applozic.mobicomkit.api.conversation.MobiComMessageService.syncMessages(MobiComMessageService.java:296)
        at com.applozic.mobicomkit.api.conversation.ConversationIntentService.onHandleWork(ConversationIntentService.java:84)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by Sunilkumarr** [comment]
@billypap1  Can you share your app AndroidManifest file and remove the confidential keys.

**Comment by billypap1** [comment]
@Sunilkumarr 
Here is my manifest 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.test.project">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <meta-data android:name="com.applozic.application.key"
        android:value="...secretKey.." />
    <meta-data android:name="activity.open.on.notification"
        android:value=".ChatScreen" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:networkSecurityConfig="@xml/network_security_config"
        android:requestLegacyExternalStorage="true"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:screenOrientation="portrait"
        android:supportsRtl="true"
        android:theme="@style/Theme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".ChatScreen" />
        <... activities ..>
        <service android:name=".SupportFiles.FcmListenerService"
            android:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
    </application>

</manifest>
```

**Comment by Sunilkumarr** [comment]
@billypap1 

In your android manifest seems like there is issue in value of package that you have passed in below meta data please pass the complete package name with activity name  in value below


```
<meta-data android:name="activity.open.on.notification"
        android:value=".ChatScreen" />
```

 
This is how it looks ConversationActivity package name that we use in pre build UI for launching the chat scren for notification tap and navigate to this activity for handling tap events.

```
<meta-data android:name="activity.open.on.notification"
            tools:node="replace" android:value="com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity" /> 

```

**Comment by billypap1** [comment]
@Sunilkumarr  
I fixed it by placing this code 
```
 <meta-data android:name="com.applozic.application.key"
        android:value="...secretKey.." />
    <meta-data android:name="activity.open.on.notification"
        android:value=".ChatScreen" />
```
inside <application> . We don't use prebuilt Applozic sdk, we are creating the UI from scratch.   
The notifications are coming as expected and works now. 
Is there any way to disable notifications coming when app is active? We need push notifications when app is inactive, in background or stopped/destroyed not when a user chat with an other.

**Comment by Sunilkumarr** [comment]
@billypap1 Cool just make sure that meta data  name with ```activity.open.on.notification``` has the value with exact package name and with activity name.


You can use this settings for disabling notification when app is open and enable it when app is closed or background


https://docs.applozic.com/docs/android-chat-theme-and-customization#notifications

**Comment by billypap1** [comment]
@Sunilkumarr Okay we enable/disable notifications on events (onStart, etc..). As we read on your documentation the Class that initialize the Applozic needs to implement ApplozicUIListener. We have implemented it with override functions but we never receive any event. (for example, when the message is received, we can see it in log but it doesn't show in onMessageReceived event, onMqttConnected  doesn't trigger also). Are we missing something? 
We use the below code:

```
if (AlAuthService.isTokenValid(context)) {
       Applozic.connectPublish(context)
    } else {
       // Getting new token from server and on success call the connect publish will be called.
     AlAuthService.refreshToken(context, object : AlCallback {
          override fun onSuccess(response: Any) {
              Applozic.connectPublish(context)
          }

          override fun onError(error: Any) {}
    })
}
```

**Comment by billypap1** [comment]
-> this code block AlEventManager.getInstance().registerUIListener("listener2", this) was on wrong position. that's why we weren't receiving any message on OnMessageReceived.

I'll close the issue, thank you for your help @Sunilkumarr
