### ISSUE TITLE
App is crashing when scroll up message list page

### ISSUE THREAD

**Issue by priyadarshi** [AppLozic/Applozic-Android-SDK#43]
App is crashing when scroll up message list page.

Log Detail:
09-17 14:18:15.245      437-437/com.mobicomkit.sample.debug I/art﹕ Late-enabling -Xcheck:jni
09-17 14:18:15.287      437-437/com.mobicomkit.sample.debug W/ActivityThread﹕ Application com.mobicomkit.sample.debug can be debugged on port 8100...
09-17 14:18:15.408      437-437/com.mobicomkit.sample.debug D/AndroidRuntime﹕ Shutting down VM
09-17 14:18:15.416      437-437/com.mobicomkit.sample.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mobicomkit.sample.debug, PID: 437
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mobicomkit.sample.debug/com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity}: java.lang.NullPointerException: Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.NullPointerException: Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference
            at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:926)
            at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1551)
            at android.support.v4.app.FragmentManagerImpl$2.run(FragmentManager.java:495)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:488)
            at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.addFragment(ConversationActivity.java:87)
            at com.applozic.mobicomkit.uiwidgets.conversation.activity.ConversationActivity.onCreate(ConversationActivity.java:113)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by priyadarshi** [comment]
Verified.
