### ISSUE TITLE
facing NetworkOnMainThreadException at SDK level.

### ISSUE THREAD

**Issue by vishalnaikawadi** [AppLozic/Applozic-Android-SDK#433]
## Goals
NA

## Expected Results
The app should not crash when performing network operation

## Actual Results
The app is crashing. Affecting 276 users.

## Steps to Reproduce
Not able to reproduce, it is very random.

## Code Sample

Stack trace:

`Fatal Exception: android.os.NetworkOnMainThreadException
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:245)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:128)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:370)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:182)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:178)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:25)
       at com.google.firebase.perf.network.InstrURLConnectionBase.getHeaderFields(InstrURLConnectionBase.java:257)
       at com.google.firebase.perf.network.InstrHttpsURLConnection.getHeaderFields(InstrHttpsURLConnection.java:144)
       at com.applozic.mobicomkit.uiwidgets.conversation.richmessaging.views.AlLinkPreview.getExpandedURLIfShortened(AlLinkPreview.java:313)
       at com.applozic.mobicomkit.uiwidgets.conversation.richmessaging.views.AlLinkPreview.getValidUrl(AlLinkPreview.java:344)
       at com.applozic.mobicomkit.uiwidgets.conversation.richmessaging.views.AlLinkPreview.access$100(AlLinkPreview.java:46)
       at com.applozic.mobicomkit.uiwidgets.conversation.richmessaging.views.AlLinkPreview$2.onClick(AlLinkPreview.java:115)
       at android.view.View.performClick(View.java:5246)
       at android.view.View$PerformClick.run(View.java:21256)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:7007)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

Applozic Android SDK version: ?
com.applozic.communication.uiwidget:mobicomkitui:5.98

Android device: Galaxy J3, Poco C3, Redmi Note 7, Redmi 6A, Galaxy A10s, Redmi 8A Dual, and many more widely used devices.

Android OS version: 5.1.1 ~ 10

Dependencies used with version: NA

**Comment by Sunilkumarr** [comment]
@vishalnaikawadi Hi, This crash has been fixed you can use the latest version: https://github.com/AppLozic/Applozic-Android-SDK/releases/tag/v5.101.0

**Comment by vishalnaikawadi** [comment]
@Sunilkumarr  when I try to upgrade the dependency I'm getting the below-mentioned error. let me know what other steps I need to perform.

>Could not resolve all files for configuration ':app:ftDebugCompileClasspath'.
   > Could not find com.applozic.communication.uiwidget:mobicomkitui:5.101.0.
     Required by:
         project :app`

**Comment by Sunilkumarr** [comment]
Hi,

Add the following maven repo URL to project-level build.gradle inside ``allProjects { repositories { ... }}:``

```
maven {
    url 'https://applozic.jfrog.io/artifactory/applozic-android-sdk'
}
```
Reference doc [link](https://docs.applozic.com/docs/android-chat-sdk#gradle-dependency)

**Comment by vishalnaikawadi** [comment]
@Sunilkumarr thanks for the support. it worked. although I have one problem. currently, we allow users to attach only images. but after upgrading to the latest version I'm seeing an option to attach gifs. I couldn't find anything to disable it.

**Comment by vishalnaikawadi** [comment]
> @Sunilkumarr thanks for the support. it worked. although I have one problem. currently, we allow users to attach only images. but after upgrading to the latest version I'm seeing an option to attach gifs. I couldn't find anything to disable it.

ok, I've found the solution. I did not find it on docs.

```
"attachmentOptions": {
   ...
    ":gif": false
  }
```
closing the issue.
